/**
 * Shared styles for Settings page components
 */

import type { CSSProperties } from 'react';

export const styles: Record<string, CSSProperties> = {
  container: {
    minHeight: '100vh',
    background: 'linear-gradient(135deg, #0f0f19 0%, #1a1a2e 100%)',
    display: 'flex',
    flexDirection: 'column',
  },
  loadingContainer: {
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'linear-gradient(135deg, #0f0f19 0%, #1a1a2e 100%)',
    gap: 16,
  },
  loadingSpinner: {
    width: 40,
    height: 40,
    border: '3px solid rgba(139, 92, 246, 0.2)',
    borderTopColor: '#8b5cf6',
    borderRadius: '50%',
    animation: 'spin 1s linear infinite',
  },
  loadingText: {
    color: '#94a3b8',
    fontSize: 14,
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '16px 24px',
    borderBottom: '1px solid rgba(139, 92, 246, 0.1)',
    background: 'rgba(15, 15, 25, 0.8)',
    backdropFilter: 'blur(10px)',
  },
  headerLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
  },
  headerRight: {
    display: 'flex',
    alignItems: 'center',
    gap: 24,
  },
  logoLink: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    textDecoration: 'none',
  },
  logoIcon: {
    width: 36,
    height: 36,
    background: 'linear-gradient(135deg, #8b5cf6 0%, #a78bfa 100%)',
    borderRadius: 10,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoText: {
    fontSize: 18,
    fontWeight: 700,
    color: '#f1f5f9',
  },
  headerDivider: {
    color: '#4b5563',
    fontSize: 20,
  },
  headerTitle: {
    fontSize: 16,
    fontWeight: 600,
    color: '#94a3b8',
  },
  navLink: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    color: '#94a3b8',
    textDecoration: 'none',
    fontSize: 14,
    padding: '8px 12px',
    borderRadius: 8,
  },
  userMenu: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
  },
  avatar: {
    width: 32,
    height: 32,
    borderRadius: '50%',
    background: 'rgba(139, 92, 246, 0.2)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  avatarImg: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  username: {
    color: '#f1f5f9',
    fontSize: 14,
    fontWeight: 500,
  },
  content: {
    display: 'flex',
    flex: 1,
  },
  sidebar: {
    width: 240,
    padding: 20,
    borderRight: '1px solid rgba(139, 92, 246, 0.1)',
    background: 'rgba(15, 15, 25, 0.4)',
    display: 'flex',
    flexDirection: 'column',
  },
  tabList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
  },
  tabButton: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    padding: '12px 14px',
    background: 'transparent',
    border: 'none',
    borderRadius: 8,
    color: '#94a3b8',
    fontSize: 14,
    cursor: 'pointer',
    textAlign: 'left',
    transition: 'all 0.2s ease',
  },
  tabButtonActive: {
    background: 'rgba(139, 92, 246, 0.1)',
    color: '#a78bfa',
  },
  sidebarFooter: {
    marginTop: 'auto',
    paddingTop: 20,
    borderTop: '1px solid rgba(139, 92, 246, 0.1)',
  },
  signOutButton: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    width: '100%',
    padding: '12px 14px',
    background: 'transparent',
    border: 'none',
    borderRadius: 8,
    color: '#f87171',
    fontSize: 14,
    cursor: 'pointer',
    textAlign: 'left',
  },
  main: {
    flex: 1,
    padding: 32,
    overflowY: 'auto',
  },
  settingsPanel: {
    maxWidth: 800,
  },
  panelTitle: {
    fontSize: 24,
    fontWeight: 700,
    color: '#f1f5f9',
    margin: '0 0 8px',
  },
  panelDescription: {
    fontSize: 14,
    color: '#94a3b8',
    margin: '0 0 32px',
  },
  error: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '12px 16px',
    background: 'rgba(239, 68, 68, 0.1)',
    borderRadius: 8,
    marginBottom: 20,
    color: '#f87171',
    fontSize: 14,
  },
  success: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '12px 16px',
    background: 'rgba(34, 197, 94, 0.1)',
    borderRadius: 8,
    marginBottom: 20,
    color: '#4ade80',
    fontSize: 14,
  },
  devNotice: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '12px 16px',
    background: 'rgba(59, 130, 246, 0.1)',
    borderRadius: 8,
    marginBottom: 24,
    color: '#60a5fa',
    fontSize: 13,
  },
  formSection: {
    marginBottom: 32,
    paddingBottom: 32,
    borderBottom: '1px solid rgba(139, 92, 246, 0.1)',
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 600,
    color: '#f1f5f9',
    margin: '0 0 16px',
  },
  sectionDescription: {
    fontSize: 13,
    color: '#94a3b8',
    margin: '-8px 0 16px',
  },
  formGroup: {
    marginBottom: 20,
  },
  label: {
    display: 'block',
    fontSize: 13,
    fontWeight: 500,
    color: '#94a3b8',
    marginBottom: 8,
  },
  input: {
    width: '100%',
    maxWidth: 400,
    padding: '12px 14px',
    background: 'rgba(15, 15, 25, 0.6)',
    border: '1px solid rgba(139, 92, 246, 0.2)',
    borderRadius: 8,
    color: '#f1f5f9',
    fontSize: 14,
    outline: 'none',
    boxSizing: 'border-box',
  },
  fieldHint: {
    fontSize: 12,
    color: '#64748b',
    marginTop: 6,
  },
  avatarUpload: {
    display: 'flex',
    alignItems: 'center',
    gap: 16,
  },
  avatarPreview: {
    width: 80,
    height: 80,
    borderRadius: '50%',
    background: 'rgba(139, 92, 246, 0.1)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    color: '#8b5cf6',
  },
  avatarPreviewImg: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  toggleRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 16,
  },
  toggleLabel: {
    fontSize: 14,
    color: '#64748b',
  },
  formActions: {
    marginTop: 24,
  },
  formRow: {
    display: 'flex',
    gap: 20,
  },
  textarea: {
    width: '100%',
    maxWidth: 600,
    padding: '12px 14px',
    background: 'rgba(15, 15, 25, 0.6)',
    border: '1px solid rgba(139, 92, 246, 0.2)',
    borderRadius: 8,
    color: '#f1f5f9',
    fontSize: 14,
    outline: 'none',
    boxSizing: 'border-box',
    resize: 'vertical',
    fontFamily: 'inherit',
    lineHeight: 1.5,
  },
  socialInput: {
    display: 'flex',
    alignItems: 'center',
    maxWidth: 400,
    background: 'rgba(15, 15, 25, 0.6)',
    border: '1px solid rgba(139, 92, 246, 0.2)',
    borderRadius: 8,
    overflow: 'hidden',
  },
  socialPrefix: {
    padding: '12px 14px',
    background: 'rgba(139, 92, 246, 0.1)',
    borderRight: '1px solid rgba(139, 92, 246, 0.2)',
    color: '#64748b',
    fontSize: 14,
    whiteSpace: 'nowrap',
  },
  socialInputField: {
    flex: 1,
    padding: '12px 14px',
    background: 'transparent',
    border: 'none',
    color: '#f1f5f9',
    fontSize: 14,
    outline: 'none',
  },
  currentPlan: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 20,
    background: 'rgba(139, 92, 246, 0.1)',
    borderRadius: 12,
    marginBottom: 32,
  },
  currentPlanInfo: {
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
  },
  currentPlanLabel: {
    fontSize: 12,
    color: '#94a3b8',
  },
  currentPlanName: {
    fontSize: 20,
    fontWeight: 700,
    color: '#f1f5f9',
  },
  planGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))',
    gap: 20,
    marginBottom: 32,
  },
  planCard: {
    position: 'relative',
    padding: 24,
    background: 'rgba(30, 30, 46, 0.6)',
    borderRadius: 12,
    border: '1px solid rgba(139, 92, 246, 0.1)',
  },
  planCardActive: {
    borderColor: '#8b5cf6',
    background: 'rgba(139, 92, 246, 0.1)',
  },
  popularBadge: {
    position: 'absolute',
    top: -10,
    right: 16,
    padding: '4px 12px',
    background: 'linear-gradient(135deg, #8b5cf6 0%, #a78bfa 100%)',
    borderRadius: 12,
    fontSize: 11,
    fontWeight: 600,
    color: '#fff',
  },
  planName: {
    fontSize: 18,
    fontWeight: 600,
    color: '#f1f5f9',
    margin: '0 0 8px',
  },
  planPrice: {
    marginBottom: 16,
  },
  priceAmount: {
    fontSize: 32,
    fontWeight: 700,
    color: '#f1f5f9',
  },
  priceInterval: {
    fontSize: 14,
    color: '#64748b',
  },
  featureList: {
    listStyle: 'none',
    padding: 0,
    margin: '0 0 20px',
  },
  featureItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
    fontSize: 13,
    color: '#94a3b8',
  },
  paymentMethod: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 20,
    background: 'rgba(15, 15, 25, 0.6)',
    borderRadius: 12,
    border: '1px dashed rgba(139, 92, 246, 0.2)',
  },
  cardPlaceholder: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    color: '#64748b',
    fontSize: 14,
  },
  emptyState: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 12,
    padding: 40,
    background: 'rgba(15, 15, 25, 0.6)',
    borderRadius: 12,
    color: '#64748b',
    fontSize: 14,
    textAlign: 'center',
  },
  upgradePrompt: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 16,
    padding: 48,
    background: 'rgba(139, 92, 246, 0.05)',
    borderRadius: 16,
    border: '1px solid rgba(139, 92, 246, 0.1)',
    textAlign: 'center',
  },
  upgradeIcon: {
    width: 64,
    height: 64,
    borderRadius: 16,
    background: 'rgba(139, 92, 246, 0.1)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#8b5cf6',
  },
  upgradeTitle: {
    fontSize: 20,
    fontWeight: 600,
    color: '#f1f5f9',
    margin: 0,
  },
  upgradeDescription: {
    fontSize: 14,
    color: '#94a3b8',
    margin: 0,
    maxWidth: 400,
  },
  statsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))',
    gap: 16,
    marginBottom: 32,
  },
  statCard: {
    padding: 20,
    background: 'rgba(30, 30, 46, 0.6)',
    borderRadius: 12,
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
  },
  statValue: {
    fontSize: 24,
    fontWeight: 700,
    color: '#f1f5f9',
  },
  statLabel: {
    fontSize: 12,
    color: '#94a3b8',
  },
  connectedAccount: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    padding: '12px 16px',
    background: 'rgba(34, 197, 94, 0.1)',
    borderRadius: 8,
    color: '#4ade80',
    fontSize: 14,
  },
  tokenList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
  },
  tokenCard: {
    padding: 16,
    background: 'rgba(30, 30, 46, 0.6)',
    borderRadius: 12,
    border: '1px solid rgba(139, 92, 246, 0.1)',
  },
  tokenHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  tokenCanvasName: {
    fontSize: 16,
    fontWeight: 600,
    color: '#f1f5f9',
    margin: '0 0 4px',
  },
  tokenCode: {
    fontSize: 12,
    color: '#64748b',
    background: 'rgba(15, 15, 25, 0.6)',
    padding: '4px 8px',
    borderRadius: 4,
  },
  tokenActions: {
    display: 'flex',
    gap: 4,
  },
  tokenMeta: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  tokenBadge: {
    padding: '4px 8px',
    background: 'rgba(139, 92, 246, 0.1)',
    borderRadius: 4,
    fontSize: 11,
    color: '#a78bfa',
  },
  tokenStats: {
    display: 'flex',
    alignItems: 'center',
    gap: 4,
    fontSize: 12,
    color: '#64748b',
    marginLeft: 'auto',
  },
  tokenOrigins: {
    fontSize: 12,
    color: '#94a3b8',
    paddingTop: 8,
    borderTop: '1px solid rgba(139, 92, 246, 0.1)',
  },
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: 'rgba(0, 0, 0, 0.7)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
    padding: 20,
  },
  modal: {
    width: '100%',
    maxWidth: 480,
    background: 'rgba(30, 30, 46, 0.95)',
    backdropFilter: 'blur(20px)',
    borderRadius: 16,
    border: '1px solid rgba(139, 92, 246, 0.2)',
    padding: 24,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 600,
    color: '#f1f5f9',
    margin: '0 0 24px',
  },
  modalActions: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: 12,
    marginTop: 24,
  },
  select: {
    width: '100%',
    padding: '12px 14px',
    background: 'rgba(15, 15, 25, 0.6)',
    border: '1px solid rgba(139, 92, 246, 0.2)',
    borderRadius: 8,
    color: '#f1f5f9',
    fontSize: 14,
    outline: 'none',
  },
  helpText: {
    fontSize: 12,
    color: '#64748b',
    marginTop: 4,
    display: 'block',
  },
  checkboxLabel: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    color: '#94a3b8',
    fontSize: 14,
    cursor: 'pointer',
  },
  widgetList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
  },
  widgetCard: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '16px 20px',
    background: 'rgba(30, 30, 46, 0.6)',
    borderRadius: 12,
    border: '1px solid rgba(139, 92, 246, 0.1)',
  },
  widgetCardInfo: {
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
  },
  widgetCardName: {
    fontSize: 15,
    fontWeight: 600,
    color: '#f1f5f9',
    margin: 0,
  },
  widgetCardCategory: {
    fontSize: 12,
    color: '#94a3b8',
    textTransform: 'capitalize',
  },
  widgetCardStats: {
    display: 'flex',
    alignItems: 'center',
    gap: 16,
    fontSize: 13,
    color: '#94a3b8',
  },
  freeTag: {
    padding: '4px 10px',
    background: 'rgba(34, 197, 94, 0.1)',
    borderRadius: 6,
    color: '#4ade80',
    fontSize: 12,
    fontWeight: 600,
  },
  priceTag: {
    padding: '4px 10px',
    background: 'rgba(139, 92, 246, 0.1)',
    borderRadius: 6,
    color: '#a78bfa',
    fontSize: 12,
    fontWeight: 600,
  },
  errorMessage: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '12px 16px',
    background: 'rgba(239, 68, 68, 0.1)',
    borderRadius: 8,
    marginBottom: 16,
    color: '#f87171',
    fontSize: 14,
  },
  draftBadge: {
    padding: '2px 8px',
    background: 'rgba(251, 191, 36, 0.1)',
    borderRadius: 4,
    color: '#fbbf24',
    fontSize: 11,
    fontWeight: 600,
    marginLeft: 8,
  },
  creatorTabs: {
    display: 'flex',
    gap: 8,
    marginBottom: 24,
    borderBottom: '1px solid rgba(139, 92, 246, 0.1)',
    paddingBottom: 12,
  },
  creatorTab: {
    padding: '8px 16px',
    background: 'transparent',
    border: 'none',
    borderRadius: 8,
    color: '#94a3b8',
    fontSize: 14,
    fontWeight: 500,
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  creatorTabActive: {
    background: 'rgba(139, 92, 246, 0.1)',
    color: '#a78bfa',
  },
  topWidgetsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  },
  topWidgetRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    padding: '12px 16px',
    background: 'rgba(30, 30, 46, 0.6)',
    borderRadius: 8,
  },
  topWidgetRank: {
    fontSize: 14,
    fontWeight: 700,
    color: '#8b5cf6',
    width: 32,
  },
  topWidgetName: {
    flex: 1,
    fontSize: 14,
    color: '#f1f5f9',
    fontWeight: 500,
  },
  topWidgetStat: {
    fontSize: 13,
    color: '#94a3b8',
  },
  topWidgetRevenue: {
    fontSize: 14,
    fontWeight: 600,
    color: '#4ade80',
    minWidth: 80,
    textAlign: 'right',
  },
  chartContainer: {
    background: 'rgba(30, 30, 46, 0.6)',
    borderRadius: 12,
    padding: 20,
  },
  barChart: {
    display: 'flex',
    alignItems: 'flex-end',
    gap: 8,
    height: 120,
  },
  barWrapper: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 4,
    height: '100%',
    justifyContent: 'flex-end',
  },
  bar: {
    width: '100%',
    minHeight: 4,
    background: 'linear-gradient(180deg, #8b5cf6 0%, #6d28d9 100%)',
    borderRadius: '4px 4px 0 0',
    transition: 'height 0.3s ease',
  },
  barLabel: {
    fontSize: 10,
    color: '#64748b',
  },
  revenueGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(120px, 1fr))',
    gap: 12,
  },
  revenueCard: {
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
    padding: 16,
    background: 'rgba(30, 30, 46, 0.6)',
    borderRadius: 12,
    textAlign: 'center',
  },
  revenueMonth: {
    fontSize: 12,
    color: '#94a3b8',
  },
  revenueAmount: {
    fontSize: 18,
    fontWeight: 700,
    color: '#4ade80',
  },
  performanceTable: {
    background: 'rgba(30, 30, 46, 0.6)',
    borderRadius: 12,
    overflow: 'hidden',
  },
  tableHeader: {
    display: 'flex',
    padding: '12px 16px',
    background: 'rgba(15, 15, 25, 0.6)',
    fontSize: 12,
    fontWeight: 600,
    color: '#64748b',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  tableRow: {
    display: 'flex',
    padding: '12px 16px',
    borderTop: '1px solid rgba(139, 92, 246, 0.1)',
    fontSize: 14,
    color: '#94a3b8',
  },
};
