/**
 * StickerNest v2 - Invite Accept Page Styles
 */

import type React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  container: {
    minHeight: '100vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'var(--sn-bg-primary, #0f0f19)',
    padding: 20,
  },
  card: {
    background: 'var(--sn-bg-secondary, #1a1a2e)',
    borderRadius: 16,
    padding: 32,
    width: 420,
    maxWidth: '100%',
    textAlign: 'center' as const,
    boxShadow: '0 8px 32px rgba(0, 0, 0, 0.4)',
    border: '1px solid var(--sn-border-primary, rgba(139, 92, 246, 0.2))',
  },
  canvasPreview: {
    width: 120,
    height: 80,
    margin: '0 auto 24px',
    borderRadius: 8,
    overflow: 'hidden',
    background: 'var(--sn-bg-tertiary, #252538)',
  },
  thumbnail: {
    width: '100%',
    height: '100%',
    objectFit: 'cover' as const,
  },
  thumbnailPlaceholder: {
    width: '100%',
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'linear-gradient(135deg, var(--sn-accent-primary) 0%, #6366f1 100%)',
  },
  title: {
    margin: '0 0 16px',
    fontSize: 24,
    fontWeight: 700,
    color: 'var(--sn-text-primary, #e2e8f0)',
  },
  inviterInfo: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    marginBottom: 16,
    color: 'var(--sn-text-primary, #e2e8f0)',
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: '50%',
    overflow: 'hidden',
    background: 'var(--sn-accent-primary, #8b5cf6)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    fontWeight: 600,
    fontSize: 16,
  },
  canvasName: {
    margin: '0 0 16px',
    fontSize: 20,
    fontWeight: 600,
    color: 'var(--sn-accent-primary, #8b5cf6)',
  },
  description: {
    color: 'var(--sn-text-secondary, #94a3b8)',
    fontSize: 14,
    margin: '0 0 24px',
    lineHeight: 1.5,
  },
  permissionsInfo: {
    background: 'var(--sn-bg-tertiary, #252538)',
    borderRadius: 8,
    padding: 16,
    marginBottom: 24,
    fontSize: 13,
    color: 'var(--sn-text-secondary, #94a3b8)',
    textAlign: 'left' as const,
  },
  message: {
    background: 'var(--sn-bg-tertiary, #252538)',
    borderRadius: 8,
    padding: 16,
    marginBottom: 24,
    fontSize: 14,
    color: 'var(--sn-text-primary, #e2e8f0)',
    fontStyle: 'italic',
    borderLeft: '3px solid var(--sn-accent-primary, #8b5cf6)',
    textAlign: 'left' as const,
  },
  userInfo: {
    fontSize: 13,
    color: 'var(--sn-text-secondary, #94a3b8)',
    marginBottom: 24,
  },
  buttonGroup: {
    display: 'flex',
    gap: 12,
    justifyContent: 'center',
  },
  primaryButton: {
    flex: 1,
    padding: '12px 24px',
    background: 'var(--sn-accent-primary, #8b5cf6)',
    color: 'white',
    border: 'none',
    borderRadius: 8,
    fontSize: 14,
    fontWeight: 600,
    cursor: 'pointer',
    textDecoration: 'none',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryButton: {
    flex: 1,
    padding: '12px 24px',
    background: 'var(--sn-bg-tertiary, #252538)',
    color: 'var(--sn-text-primary, #e2e8f0)',
    border: '1px solid var(--sn-border-primary, rgba(139, 92, 246, 0.2))',
    borderRadius: 8,
    fontSize: 14,
    fontWeight: 500,
    cursor: 'pointer',
    textDecoration: 'none',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  spinner: {
    width: 32,
    height: 32,
    border: '3px solid var(--sn-border-primary, rgba(139, 92, 246, 0.2))',
    borderTopColor: 'var(--sn-accent-primary, #8b5cf6)',
    borderRadius: '50%',
    animation: 'spin 1s linear infinite',
    margin: '0 auto',
  },
  loadingText: {
    color: 'var(--sn-text-secondary, #94a3b8)',
    fontSize: 14,
    marginTop: 16,
  },
  iconSuccess: {
    width: 64,
    height: 64,
    borderRadius: '50%',
    background: 'rgba(34, 197, 94, 0.2)',
    color: 'var(--sn-success, #22c55e)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 32,
    fontWeight: 700,
    margin: '0 auto 24px',
  },
  iconError: {
    width: 64,
    height: 64,
    borderRadius: '50%',
    background: 'rgba(239, 68, 68, 0.2)',
    color: 'var(--sn-error, #ef4444)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 32,
    fontWeight: 700,
    margin: '0 auto 24px',
  },
  iconExpired: {
    width: 64,
    height: 64,
    borderRadius: '50%',
    background: 'rgba(148, 163, 184, 0.2)',
    color: 'var(--sn-text-secondary, #94a3b8)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 32,
    fontWeight: 700,
    margin: '0 auto 24px',
  },
};
