/**
 * StickerNest v2 - Shared With Me Page Styles
 */

import type React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  container: {
    minHeight: '100vh',
    background: 'var(--sn-bg-primary, #0f0f19)',
    padding: '32px 24px',
  },
  header: { maxWidth: 1200, margin: '0 auto 32px' },
  title: { margin: 0, fontSize: 28, fontWeight: 700, color: 'var(--sn-text-primary, #e2e8f0)' },
  subtitle: { margin: '8px 0 0', fontSize: 14, color: 'var(--sn-text-secondary, #94a3b8)' },
  tabs: {
    maxWidth: 1200,
    margin: '0 auto 24px',
    display: 'flex',
    gap: 8,
    borderBottom: '1px solid var(--sn-border-secondary, rgba(255,255,255,0.1))',
  },
  tab: {
    padding: '12px 16px',
    background: 'transparent',
    border: 'none',
    borderBottom: '2px solid transparent',
    color: 'var(--sn-text-secondary, #94a3b8)',
    fontSize: 14,
    fontWeight: 500,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    marginBottom: -1,
  },
  tabActive: { color: 'var(--sn-text-primary, #e2e8f0)', borderBottomColor: 'var(--sn-accent-primary, #8b5cf6)' },
  badge: { padding: '2px 8px', background: 'var(--sn-bg-tertiary, #252538)', borderRadius: 12, fontSize: 11, fontWeight: 600 },
  content: { maxWidth: 1200, margin: '0 auto' },
  loading: { display: 'flex', flexDirection: 'column' as const, alignItems: 'center', justifyContent: 'center', padding: 64, color: 'var(--sn-text-secondary, #94a3b8)' },
  spinner: { width: 32, height: 32, border: '3px solid var(--sn-border-primary, rgba(139, 92, 246, 0.2))', borderTopColor: 'var(--sn-accent-primary, #8b5cf6)', borderRadius: '50%', animation: 'spin 1s linear infinite', marginBottom: 16 },
  emptyState: { display: 'flex', flexDirection: 'column' as const, alignItems: 'center', justifyContent: 'center', padding: 64, textAlign: 'center' as const },
  emptyTitle: { margin: '0 0 8px', fontSize: 18, fontWeight: 600, color: 'var(--sn-text-primary, #e2e8f0)' },
  emptyDescription: { margin: '0 0 24px', fontSize: 14, color: 'var(--sn-text-secondary, #94a3b8)' },
  primaryButton: { padding: '12px 24px', background: 'var(--sn-accent-primary, #8b5cf6)', color: 'white', border: 'none', borderRadius: 8, fontSize: 14, fontWeight: 600, cursor: 'pointer', textDecoration: 'none' },
  grid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))', gap: 24 },
  card: { background: 'var(--sn-bg-secondary, #1a1a2e)', borderRadius: 12, overflow: 'hidden', border: '1px solid var(--sn-border-primary, rgba(139, 92, 246, 0.2))', transition: 'transform 0.2s, box-shadow 0.2s' },
  thumbnailLink: { display: 'block', aspectRatio: '16 / 9' },
  thumbnail: { width: '100%', height: '100%', objectFit: 'cover' as const },
  thumbnailPlaceholder: { width: '100%', height: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'linear-gradient(135deg, var(--sn-bg-tertiary) 0%, var(--sn-bg-secondary) 100%)' },
  cardContent: { padding: 16 },
  canvasName: { display: 'block', fontSize: 16, fontWeight: 600, color: 'var(--sn-text-primary, #e2e8f0)', textDecoration: 'none', marginBottom: 8 },
  cardMeta: { display: 'flex', alignItems: 'center', gap: 8, fontSize: 12, color: 'var(--sn-text-secondary, #94a3b8)', marginBottom: 12 },
  cardFooter: { display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
  date: { fontSize: 11, color: 'var(--sn-text-muted, #64748b)' },
  leaveButton: { padding: '4px 12px', background: 'transparent', border: '1px solid rgba(239, 68, 68, 0.3)', borderRadius: 4, color: 'var(--sn-error, #ef4444)', fontSize: 11, cursor: 'pointer' },
  inviteList: { display: 'flex', flexDirection: 'column' as const, gap: 12 },
  inviteCard: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: 16, background: 'var(--sn-bg-secondary, #1a1a2e)', borderRadius: 8, border: '1px solid var(--sn-border-primary, rgba(139, 92, 246, 0.2))', gap: 16 },
  inviteInfo: { flex: 1, minWidth: 0 },
  inviteTitle: { fontSize: 14, color: 'var(--sn-text-primary, #e2e8f0)', marginBottom: 8 },
  inviteMeta: { display: 'flex', alignItems: 'center', gap: 8, fontSize: 12, color: 'var(--sn-text-secondary, #94a3b8)', flexWrap: 'wrap' as const },
  inviteActions: { display: 'flex', gap: 8, flexShrink: 0 },
  acceptButton: { padding: '8px 16px', background: 'var(--sn-accent-primary, #8b5cf6)', border: 'none', borderRadius: 6, color: 'white', fontSize: 13, fontWeight: 500, cursor: 'pointer' },
  viewButton: { padding: '8px 16px', background: 'var(--sn-bg-tertiary, #252538)', border: '1px solid var(--sn-border-primary, rgba(139, 92, 246, 0.2))', borderRadius: 6, color: 'var(--sn-text-primary, #e2e8f0)', fontSize: 13, textDecoration: 'none' },
};
